import type { Config } from "jest";
import nextJest from "next/jest.js";

const createJestConfig = nextJest({
  dir: "./",
});

const customConfig: Config = {
  coverageProvider: "v8",
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
};

// All ESM-only packages in node_modules that Jest's CJS transformer must not skip.
// Generated by: node -e "..." to find packages with "type":"module" in their package.json.
const esmPackages = [
  "bail",
  "ccount",
  "character-entities",
  "character-entities-html4",
  "character-entities-legacy",
  "comma-separated-tokens",
  "decode-named-character-reference",
  "devlop",
  "hast-util-from-parse5",
  "hast-util-parse-selector",
  "hast-util-raw",
  "hast-util-sanitize",
  "hast-util-to-html",
  "hast-util-to-parse5",
  "hast-util-whitespace",
  "hastscript",
  "html-void-elements",
  "is-plain-obj",
  "longest-streak",
  "mdast-util-from-markdown",
  "mdast-util-phrasing",
  "mdast-util-to-hast",
  "mdast-util-to-markdown",
  "mdast-util-to-string",
  "micromark",
  "micromark-core-commonmark",
  "micromark-factory-destination",
  "micromark-factory-label",
  "micromark-factory-space",
  "micromark-factory-title",
  "micromark-factory-whitespace",
  "micromark-util-character",
  "micromark-util-chunked",
  "micromark-util-classify-character",
  "micromark-util-combine-extensions",
  "micromark-util-decode-numeric-character-reference",
  "micromark-util-decode-string",
  "micromark-util-encode",
  "micromark-util-html-tag-name",
  "micromark-util-normalize-identifier",
  "micromark-util-resolve-all",
  "micromark-util-sanitize-uri",
  "micromark-util-subtokenize",
  "micromark-util-symbol",
  "micromark-util-types",
  "parse5",
  "property-information",
  "remark",
  "remark-html",
  "remark-parse",
  "remark-stringify",
  "space-separated-tokens",
  "stringify-entities",
  "trim-lines",
  "trough",
  "unified",
  "unist-util-is",
  "unist-util-position",
  "unist-util-stringify-position",
  "unist-util-visit",
  "unist-util-visit-parents",
  "vfile",
  "vfile-location",
  "vfile-message",
  "web-namespaces",
  "zwitch",
];

export default async () => {
  const config = await createJestConfig(customConfig)();

  config.transformIgnorePatterns = [
    `/node_modules/(?!(${esmPackages.join("|")})/)`
  ];

  return config;
};
